default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.0.0
    hooks:
    -   id: gitleaks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: requirements-txt-fixer
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
            - -l 120
    
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    - id: codespell
      exclude: >
        (?x)^(
            .*\.csv|
            azalabs/user_web_app/public/static/jquery-3.5.1.min.js
        )$
      args:
        - --quiet-level=2
        - -L referer, ans,
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
      - id: gitleaks
        args:
            - protect
            - --verbose
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
    - id: tflint
    - id: terraform-fmt
